contents:
  - name: 组合数
    codes:
      - comb.hpp
  - name: 计算几何（新）
    codes:
      - flat-geometry.hpp
  - name: 计算几何（jiangly）
    codes:
      - ../../jiangly/math/09B-Flat-Geometry.hpp
  - name: 类欧几里得 (floor_sum)
    codes:
      - floor-sum.hpp
  - name: 卷积
    codes:
      - conv.hpp
  - name: 按值域预处理的快速 gcd
    codes:
      - gcd.hpp
  - name: 拉格朗日插值
    codes:
      - lagrange.hpp
  - name: 线性代数
    codes:
      - linear.hpp
  - name: modint
    codes:
      - mod-int.hpp
