contents:
  - name: 二进制警报
    codes:
      - binary-alarm.hpp
  - name: 笛卡尔树
    codes:
      - cartesian.hpp
  - name: 珂朵莉树
    codes:
      - chtholly.hpp
  - name: 并查集
    directory: dsu
  - name: 动态 bitset（效率极低）
    codes:
      - dynamic-bitset.hpp
  - name: 哈希表
    codes:
      - hashmap.hpp
  - name: pbds 平衡树
    codes:
      - pbds-balance-tree.hpp
  - name: 滑动窗口
    codes:
      - sliding-window.hpp
  - name: 安全哈希 (Splitmix)
    codes:
      - splitmix.hpp
